[package]
name = "ui"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true