[paths]
sqlite = "sqlite.db"
tasks = "tasks.db"
vectors = "vectors/"
blobs = "blobs/"
embed_cache = "embed_cache.db"
logs_dir = "logs/"

[nlu]
embed_model = "bge3"
rerank_model = "bg3"
top_k_semantic = 128
top_k_rerank = 32

[policy]
max_tokens = 8192
max_bg3_docs = 64
allow_net = false

[scheduler]
reindex_interval = "1h"
stale_review_interval = "24h"
