[package]
name = "memory"
version.workspace = true
edition.workspace = true

[features]
default = []
use_real_onnx = []

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rusqlite = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }

# Для векторных операций
ndarray = "0.16"

# Для эмбеддингов и reranking через ONNX Runtime
reqwest = { workspace = true, features = ["stream"] }
ort = { version = "2.0.0-rc.10", features = ["download-binaries", "load-dynamic", "cuda", "tensorrt", "coreml", "directml"] }
tokenizers = "0.21"


# Для криптографии и хеширования
blake3 = "1.5"

# Для файловых операций
walkdir = { workspace = true }
tempfile = { workspace = true }

# Для чанкинга и индексации
glob = "0.3"
notify = "6.1"
futures = "0.3"
futures-util = "0.3"

[dev-dependencies]
tempfile = { workspace = true }
tokio-test = "0.4"
tracing-subscriber = "0.3"