name: docker-cpu-smoke

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]
    paths:
      - 'scripts/docker/**'
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CPU image
        run: |
          docker build -t magray:cpu -f scripts/docker/Dockerfile.cpu .

      - name: Smoke test --version
        run: |
          docker run --rm magray:cpu /usr/local/bin/magray --version

      - name: Smoke test --help
        run: |
          docker run --rm magray:cpu /usr/local/bin/magray --help | head -n 40

      - name: Optional status (non-fatal)
        run: |
          docker run --rm magray:cpu /usr/local/bin/magray status || true